name: go

on:
  push:
    branches:
      - main
    tags:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Linters (Static Analysis) for Go
    steps:
      - name: Checkout code into the Go module directory.
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19.x

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Linting & vetting.
        env:
          GOBIN: /tmp/.bin
        run: make lint
  tests:
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        go: [ '1.16.x', '1.17.x', '1.18.x', '1.19.x']
        platform: [ubuntu-latest, macos-latest]

    name: Unit tests on Go ${{ matrix.go }} ${{ matrix.platform }}
    steps:
      - name: Checkout code into the Go module directory.
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Run unit tests.
        env:
          GOBIN: /tmp/.bin
        run: make test
